charts: 
- yKey: train/episode/rew_total/mean
xKey: iterations
- yKey: train/episode/rew_tracking_lin_vel/mean
xKey: iterations
- yKey: train/episode/rew_tracking_contacts_shaped_force/mean
xKey: iterations
- yKey: train/episode/rew_action_smoothness_1/mean
xKey: iterations
- yKey: train/episode/rew_action_smoothness_2/mean
xKey: iterations
- yKey: train/episode/rew_tracking_contacts_shaped_vel/mean
xKey: iterations
- yKey: train/episode/rew_orientation_control/mean
xKey: iterations
- yKey: train/episode/rew_dof_pos/mean
xKey: iterations
- yKey: train/episode/command_area_trot/mean
xKey: iterations
- yKey: train/episode/max_terrain_height/mean
xKey: iterations
- type: video
glob: "videos/*.mp4"
- yKey: adaptation_loss/mean
xKey: iterations
