"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class camera_message_rect_wide(object):
    __slots__ = ["data"]

    def __init__(self):
        self.data = ""

    def encode(self):
        buf = BytesIO()
        buf.write(camera_message_rect_wide._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(bytearray(self.data[:34800]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != camera_message_rect_wide._get_packed_fingerprint():
            raise ValueError("Decode error")
        return camera_message_rect_wide._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = camera_message_rect_wide()
        self.data = buf.read(34800)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if camera_message_rect_wide in parents: return 0
        tmphash = (0xc3e9f058530b2a8b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if camera_message_rect_wide._packed_fingerprint is None:
            camera_message_rect_wide._packed_fingerprint = struct.pack(">Q", camera_message_rect_wide._get_hash_recursive([]))
        return camera_message_rect_wide._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

